name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure pypirc
        echo "[distutils]" > ~/.pypirc
        echo "index-servers = github" >> ~/.pypirc
        echo "" >> ~/.pypirc
        echo "[github]" >> ~/.pypirc
        echo "repository = https://maven.pkg.github.com/DannyMExe/rag-package" >> ~/.pypirc
        echo "username = __token__" >> ~/.pypirc
        echo "password = ${GITHUB_TOKEN}" >> ~/.pypirc
        
        # Upload package
        twine upload --repository github dist/* --verbose